### ISSUE TITLE
update the docker image to LLVM 10 

### ISSUE THREAD

**Issue by clangenb** [chevdor/srtool-actions#2]
We have a substrate-runtime dependency that needs LLVM 10. It would be great, if the LLVM version is updated in the docker image.

As rustc 1.53 requires LLVM >=10, this will be a necessary step anyhow.

**Comment by chevdor** [comment]
Thanks @clangenb I will look into that.

**Comment by clangenb** [comment]
Splendid, thank you!

**Comment by chevdor** [comment]
@clangenb I will be closing this issue now for the reasons mentioned below but I think that your "problem" should be fixed now:
- the srtool-actions from this repo are only calling srtool. It calls the latest version by default, unless the user specifies otherwise
- now the interesting part:  the latest release of `srtool` (https://gitlab.com/chevdor/srtool/-/tags/v0.9.14) beings support for rustc **stable** (1.53.0)

So if you use `srtool-actions` from this repo and do NOT provide the `tag` input (recommended) or use `tag: 1.53.0`, you will be building on rustc stable using 1.53.0.

**Comment by clangenb** [comment]
Thanks. I can confirm that it works 👍
